version: 5.1.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  nuget_token:
    secure: f/XPPzBiOEmc6sz+tLNtDeKR8Lu9xg+ekJuTasmT+iIaQT2xrgw9DnPEHT4/F4ccUIiVfMyg2eLDR6EyiyRdSgOLToUgOQAkXxD89InogY8=
  github_token:
    secure: uVxlPx0d4HQdnxj4NhsrCCnQ0iqxmUDUPqPGRheiHt5Dp7pmOtXdGIYy52Y5rRQkLIl7He4wAH1W8nTOU+yahTec4+tbp0B8JTX/Mly8aVE=
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore .\Leaf.xNet.sln
build:
  project: Leaf.xNet.sln
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: Leaf.xNet\bin\Release\net462
  name: net462
- path: Leaf.xNet\bin\Release\netcoreapp2.0
  name: netcoreapp2.0
deploy:
- provider: NuGet
  api_key:
    secure: LAP1RRHzZP5slfjtjZY7WQ==
  skip_symbols: true
  on:
    branch: master
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: Leaf.xNet v$(appveyor_build_version)
  auth_token:
    secure: NQtMOO3yB309cDK/pFWRiQ==
  artifact: net462;netcoreapp2.0
  on:
    branch: master
notifications:
- provider: Email
  to:
  - mixtape774@gmail.com
  subject: AppVeuor - Leaf.xNet Build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
only_commits:
  files:
    - appveyor.yml
    - Leaf.xNet.sln
    - Leaf.xNet/Leaf.xNet.csproj
    - Leaf.xNet/**/*.cs
    - Leaf.xNet/**/*.resx
